/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.intento11;

import javax.swing.ImageIcon;

/**
 *
 * @author miguel
 */
public class elegir_fondo extends javax.swing.JFrame {

    int tablero_1;
    /**
     * Creates new form elegir_fondo
     */
    
    public elegir_fondo() {
        initComponents();
        fondo_fondos.setIcon(new ImageIcon("src/main/java/fondo/fondo-tiradas.png"));
        imgtab1.setIcon(new ImageIcon("src/main/java/fondo/tab1.png"));
        imgtab2.setIcon(new ImageIcon("src/main/java/fondo/tab2.png"));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JLabel();
        tab2 = new javax.swing.JLabel();
        imgtab1 = new javax.swing.JLabel();
        imgtab2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fondo_fondos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab1.setFont(new java.awt.Font("Onyx", 1, 24)); // NOI18N
        tab1.setForeground(new java.awt.Color(0, 255, 255));
        tab1.setText("TABLERO   1");
        jPanel1.add(tab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        tab2.setFont(new java.awt.Font("Onyx", 1, 24)); // NOI18N
        tab2.setForeground(new java.awt.Color(255, 255, 0));
        tab2.setText("TABLERO   2");
        jPanel1.add(tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        imgtab1.setText("jLabel1");
        jPanel1.add(imgtab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 150, 150));

        imgtab2.setText("jLabel1");
        jPanel1.add(imgtab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 150, 150));

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jButton2.setText("seleccionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));
        jPanel1.add(fondo_fondos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         elegir_njugadores2 nj2 = new elegir_njugadores2();
        nj2.setVisible(true);
        dispose();
        tablero_1 = 1;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        elegir_njugadores nj = new elegir_njugadores();
        nj.setVisible(true);
        dispose();
        tablero_1 = 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(elegir_fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(elegir_fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(elegir_fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(elegir_fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new elegir_fondo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo_fondos;
    private javax.swing.JLabel imgtab1;
    private javax.swing.JLabel imgtab2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tab1;
    private javax.swing.JLabel tab2;
    // End of variables declaration//GEN-END:variables
}
