/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.intento11;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author miguel
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    jLabel2.setIcon(new ImageIcon("src/main/java/fondo/fondo-tiradas.png"));
    jLabel4.setIcon(new ImageIcon("src/main/java/fondo/negro.png"));
    jLabel1.setText("<html><H3><font color=\"E1F800\"> Lanza el dado para que se mueva tu ficha."
    + " llega al final antes que tu competencia."
    + " aprovechate de las escaleras para subir espacios y adelantarte,"
    + " pero ten cuidado<br> con las serpientes que te haran bajar y retoceder."
    + " Disfruta de esta aventura y DIVIERTETE !!!! </font></H3><html>");
    
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        unjugador = new javax.swing.JButton();
        verregistros = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        prueba_mari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unjugador.setBackground(new java.awt.Color(0, 0, 0));
        unjugador.setFont(new java.awt.Font("Yu Gothic Medium", 3, 24)); // NOI18N
        unjugador.setForeground(new java.awt.Color(51, 255, 51));
        unjugador.setText("jugar");
        unjugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unjugadorActionPerformed(evt);
            }
        });
        jPanel1.add(unjugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 240, 40));

        verregistros.setBackground(new java.awt.Color(0, 0, 0));
        verregistros.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        verregistros.setForeground(new java.awt.Color(51, 255, 51));
        verregistros.setText("ver registros de partidas");
        verregistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verregistrosActionPerformed(evt);
            }
        });
        jPanel1.add(verregistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        salir.setBackground(new java.awt.Color(0, 0, 0));
        salir.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        salir.setForeground(new java.awt.Color(51, 255, 0));
        salir.setText("salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        prueba_mari.setText("prueba mari");
        prueba_mari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prueba_mariActionPerformed(evt);
            }
        });
        jPanel1.add(prueba_mari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));
        prueba_mari.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("ESCALERAS  Y   SERPIENTES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 480, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lanza el dado para que se mueva tu ficha."
            + " llega al final antes que tu competencia."
            + " aprovechate de las escaleras para subir espacios y adelantarte,"
            + " pero ten cuidado con las serpientes que te haran bajar y retoceder."
            + " Disfruta de esta aventura y DIVIERTETE !!!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 96, 220, 310));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 210, 200));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 560, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_salirActionPerformed

    private void unjugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unjugadorActionPerformed
        // TODO add your handling code here:
         elegir_fondo tab = new elegir_fondo();
        tab.setVisible(true);
        dispose();
    }//GEN-LAST:event_unjugadorActionPerformed

    private void verregistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verregistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verregistrosActionPerformed

    private void prueba_mariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prueba_mariActionPerformed
        // TODO add your handling code here:
        pruebaxd tab = new pruebaxd();
        tab.setVisible(true);
        dispose();
    }//GEN-LAST:event_prueba_mariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton prueba_mari;
    private javax.swing.JButton salir;
    private javax.swing.JButton unjugador;
    private javax.swing.JButton verregistros;
    // End of variables declaration//GEN-END:variables
}
